# Generated by Django 4.2.4 on 2024-11-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expected_graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
