# Generated by Django 4.2.4 on 2024-11-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_objectives_slug_profession_slug_referral_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profession',
            old_name='name',
            new_name='profession_name',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='name',
            new_name='referral_name',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='name',
            new_name='university_name',
        ),
    ]
