# Generated by Django 4.2.4 on 2024-11-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_name_profession_profession_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectives',
            old_name='name',
            new_name='objective_name',
        ),
        migrations.AlterField(
            model_name='objectives',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='profession',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True),
        ),
    ]
