# Generated by Django 4.2.4 on 2024-11-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_name_objectives_objective_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectives',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='university',
            name='slug',
        ),
    ]
