# Generated by Django 4.2.4 on 2024-11-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_objectives_slug_remove_profession_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='country_name',
            field=models.CharField(default='india', max_length=200),
        ),
    ]
