# Generated by Django 4.2.4 on 2024-11-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expected_graduation_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
